---
port_profiles:
  - profile: VLAN_10
    vlans: 10
    mode: access
    spanning_tree_portfast: edge
    port_channel:
      mode: active    
  - profile: VLAN_20
    vlans: 10
    mode: access
    spanning_tree_portfast: edge
    port_channel:
      mode: active    