---
tenants:
  - name: ACME
    mac_vrf_vni_base: 10000
    evpn_l2_multicast:
      enabled: true
      underlay_l2_multicast_group_ipv4_pool: 239.99.99.0/24
    vrfs:
      - name: VRF_A
        vtep_diagnostic:
          loopback: 99
          loopback_ip_range: 192.168.109.0/24
        evpn_l3_multicast:
          enabled: true
          evpn_underlay_l3_multicast_group: 239.0.100.1
        vrf_vni: 10
        svis:
          - id: 10
            name: DMZ
            enabled: true
            ip_address_virtual: 10.1.10.1/24
            evpn_l2_multicast:
              enabled: true
            evpn_l3_multicast:
              enabled: true
          - id: 20 
            name: Internal
            enabled: true
            ip_address_virtual: 10.1.20.1/24
            evpn_l2_multicast:
              enabled: true
            evpn_l3_multicast:
              enabled: true